# Generated by Django 2.0.1 on 2018-03-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_parkingspot_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspot',
            old_name='token',
            new_name='uuid',
        ),
    ]
