# Generated by Django 2.0.1 on 2018-03-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_auto_20180303_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='id',
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='uuid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
