# Generated by Django 2.0.1 on 2018-03-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0005_auto_20180303_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
