# Generated by Django 2.0.1 on 2018-03-03 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0006_auto_20180303_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='timestamp',
            new_name='time_in',
        ),
        migrations.AddField(
            model_name='state',
            name='time_out',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
