# Generated by Django 2.0.1 on 2018-03-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0008_auto_20180304_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='max_hours',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.25, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='time_out',
            field=models.DateTimeField(blank=True),
        ),
    ]
