# Generated by Django 2.0.1 on 2018-03-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0009_auto_20180304_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='days_enforced',
            field=models.CharField(default='A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='start_enforcing',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='stop_enforcing',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
