# Generated by Django 2.0.1 on 2018-03-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0010_auto_20180304_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='max_hours',
            field=models.CharField(max_length=20),
        ),
    ]
