# Generated by Django 2.0.1 on 2018-03-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0011_auto_20180304_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
